source:      .
destination: _site
layouts_dir:     _layouts
exclude: [node_modules, README.md, CNAME, package.json, src, Guardfile]

future:      true

permalink:     :title

markdown:      kramdown
markdown_ext:  md

defaults:
  is_page: false

excerpt_separator: "\n\n"

safe:        false
host:        127.0.0.1
port:        4000
lsi:         false
